integration:
  exchange:
    SoapCallExchangeRule:
      endpoint: insis_pam_endpoint
      securityMode: UsernamePassword
      username: 'insis-username'
      password: 'insis-password'
      ignoreNamespaces: 'insis-ignoreNamespaces'
      jsonSchema: InsisPAM
  transformation:
    DefaultTransformationRule:
      out:
        - mappings:
            - param: soapAction
              value: convertQuotationToApplication
            - param: requestType
              value: CnvrtQuotToApplRqType
        - mappings:
            - element: policy.contract.policy-id
              payload: PolicyID
      in:
        - mappings:
            - element: policy.status.policy-status
              value: '-2'
