page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component:
    InsisTwoLevelStepperNavigationPage: {}
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.agent.title
