page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component: InsisTwoLevelStepperNavigationPage
  sections:
    - component:
        IceFlexSection:
          tags:
            - pull-right
          grid:
            rows:
              - cols:
                  - size: auto
                    elements:
                      - name: continue
                css: mat-headline u-mb-0
                align: center
                gap: 10px
      css: button-width-100 u-mb-3
