page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component:
    InsisTwoLevelStepperNavigationPage: {}
  sections:
    - header
    - beneficiaries.is-standard-beneficiary
    - beneficiaries.details
    - beneficiaries.go-to-next-page
    - policy.premiums-taxes-fees-discounts-loadings
    - quote.download
    - policy.summary
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.beneficiaries.title
      pageTitleKey: pages.2.application.beneficiaries.title
      shortTitleKey: pages.2.application.beneficiaries.title
