page:
  component:
    InsisTwoLevelStepperNavigationPage: {}
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.agent.title
      pageTitleKey: pages.2.application.agent.title
      shortTitleKey: pages.2.application.agent.title
  sections:
    - header
    - vehicle.ownership
    - continue
    - need-more-info
    - policy.premiums-taxes-fees-discounts-loadings
    - policy.summary
