section:
  component:
    IceFlexSection:
      tags:
        - pull-right
      grid:
        rows:
          - cols:
              - size: 100%
                elements:
                  - name: go-to-application
      css: button-width-100 u-mb-3
