action:
  title: calls convert quote to application
  execution:
    - IntegrationExecutionRule:
        integration: 910211.risks.life.insis-policy.appilcation.register
    - IntegrationExecutionRule:
        integration: 910211.risks.life.insis-policy.get-premiums
    - NavigateToPageExecutionRule:
        direction: next
