page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component:
    InsisTwoLevelStepperNavigationPage: {}
  sections:
    - component:
        IceFlexSection:
          grid:
            rows:
              - cols:
                  - size: auto
                    size.xs: auto
                    css: u-mt-4
                    elements:
                      - name: go-to-next-page
