integration:
  exchange:
    SoapCallExchangeRule:
      endpoint: insis_pam_endpoint
      securityMode: UsernamePassword
      username: 'env:insis-username'
      password: 'env:insis-password'
      ignoreNamespaces: 'env:insis-ignoreNamespaces'
      soapAction: modifyApplication
      requestType: ModifyApplRqType
      responseType: ModifyApplRsType
      jsonSchema: InsisPAM
  transformation:
    DefaultTransformationRule:
      additional: insis
      dateFormat: YYYY-MM-DD
      dateTimeFormat: 'YYYY-MM-DDThh:mm:ss'
      extends: 910211.risks.life.insis-policy.save
      in: {}
      out:
        - mappings:
            - param: soapAction
              value: modifyApplication
            - param: requestType
              value: ModifyApplRqType
        - fromIdx:
            array: datamodel.policy.insured.person-objects
          toIdx:
            array: payload.Insureds.Insured
            append: false
            condition: 1 == 1
          mappings:
            - value: null
              payload: Insureds.Insured[n].InsuredEntity.OAccidentInsured.AccinsType

        - fromIdx:
            array: datamodel.policy.participants.beneficiaries
          toIdx:
            array: payload.InsuranceConditions.Participants.Participant
            append: true
          if: datamodel.policy.participants.is-standard-beneficiary == false
          mappings:
            - element: policy.participants.beneficiaries~person.gender
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.Gender
            - element: policy.participants.beneficiaries~person.birthdate
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.BirthDate
            - element: policy.participants.beneficiaries~person.last-name
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.Name.Family
            - element: policy.participants.beneficiaries~person.first-name
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.Name.Given
            - value: 'BENEFICENT'
              payload: InsuranceConditions.Participants.Participant[n].ParticipantRole
            - value: 'ACTIVE'
              payload: InsuranceConditions.Participants.Participant[n].Status
            - value: 'ENGLISH'
              payload: InsuranceConditions.Participants.Participant[n].Language

        - fromIdx:
            array: datamodel.policy.participants.beneficiaries
            condition: person.pid == null
          toIdx:
            useSourceIndex: true
          if: datamodel.policy.participants.is-standard-beneficiary == false
          mappings:
            - value: ''
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.PID

        - fromIdx:
            array: datamodel.policy.participants.beneficiaries
            condition: person.pid != null
          toIdx:
            useSourceIndex: true
          if: datamodel.policy.participants.is-standard-beneficiary == false
          mappings:
            - element: policy.participants.beneficiaries~person.pid
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.PID

        - fromIdx:
            index: '[datamodel.policy.participants.beneficiaries.length + 1 ]'
          toIdx:
            array: payload.InsuranceConditions.Participants.Participant
            append: true
          mappings:
            - principal: pid
              payload: InsuranceConditions.Participants.Participant[n].Entity.PersonalData.PID
            - value: 'PHOLDER'
              payload: InsuranceConditions.Participants.Participant[n].ParticipantRole
            - value: 'ACTIVE'
              payload: InsuranceConditions.Participants.Participant[n].Status
            - value: 'ENGLISH'
              payload: InsuranceConditions.Participants.Participant[n].Language
            # - value: '-1'
            #   payload: InsuranceConditions.Participants.Participant[n].PolicyBankAccounts.PolicyBankAccount[0].BankAccount.BankPID
            # - element: policy.participants.payor.iban
            #   payload: InsuranceConditions.Participants.Participant[n].PolicyBankAccounts.PolicyBankAccount[0].BankAccount.AccountNo
