page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component:
    InsisTwoLevelStepperNavigationPage: {}
  sections:
    - beneficiaries.go-to-next-page-pulled-right
    - beneficiaries.is-standard-beneficiary
    - beneficiaries.details
    - beneficiaries.add-beneficiary
    - policy.premiums-taxes-fees-discounts-loadings
