integration:
  exchange:
    SoapCallExchangeRule:
      endpoint: insis_pam_endpoint
      securityMode: UsernamePassword
      username: 'insis-username'
      password: 'insis-password'
      ignoreNamespaces: 'insis-ignoreNamespaces'
      jsonSchema: InsisPAM
  transformation:
    DefaultTransformationRule:
      additional: insis
      dateFormat: YYYY-MM-DD
      dateTimeFormat: 'YYYY-MM-DDThh:mm:ss'
      extends: 920101.motor.insis-policy.save
      in: {}
      out:
        - mappings:
            - param: soapAction
              value: modifyApplication
            - param: requestType
              value: ModifyApplRqType
            - param: responseType
              value: ModifyApplRsType
        - fromIdx:
            array: datamodel.policy.participants.holder.person.accounts
            condition: datamodel.policy.participants.payor.iban == iban
          toIdx:
            array: payload.InsuranceConditions.Participants.Participant
            condition: ParticipantRole == 'PHOLDER'
          mappings:
            - element: policy.participants.holder.participant-id
              payload: InsuranceConditions.Participants.Participant[n].ParticipantID
            - element: policy.participants.holder.person.accounts~bank-id
              payload: InsuranceConditions.Participants.Participant[n].PolicyBankAccounts.PolicyBankAccount[0].BankAccID
            - value: 'BILLING'
              payload: InsuranceConditions.Participants.Participant[n].PolicyBankAccounts.PolicyBankAccount[0].AccountPurpose
