environment:
  # customer_data: process.env.BASEURL
  # customer_documents: process.env.BASEURLDOCS
  insis-pdm-endpoint: http://10.26.20.2:7705/insisws/InsisPDMPort
  insis_pam_endpoint: http://10.26.20.2:7705/insisws/InsisPAMPort
  insis-generic-endpoint: http://10.26.20.2:7705/insisws/InsisGenericWSPort
  insis-quick-quote-client-pid: "987654321"
  insis-username: insis_gen_v10
  insis-password: insis_gen_v10
  utility_endpoint: http://192.168.0.162/ccmmwebservices/CIUtilityWs.asmx
  customer_endpoint: http://192.168.0.162/ccmmwebservices/CICustomerWs.asmx
  phonenumber_endpoint: http://192.168.0.162/ccmmwebservices/CIPhoneNumberWs.asmx
  skillset_endpoint: http://192.168.0.162/ccmmwebservices/CISkillsetWs.asmx
  communication_endpoint: http://192.168.0.162/ccmmwebservices/CIWebCommsWs.asmx
  insis-ignoreNamespaces:
    - insis
  mocks:
    - insis_pam_endpoint
