page:
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  component:
    InsisTwoLevelStepperNavigationPage: {}
