integration:
  exchange:
    SoapCallExchangeRule:
      endpoint: insis_pam_endpoint
      securityMode: UsernamePassword
      username: insis-username
      password: insis-password
      ignoreNamespaces: insis-ignoreNamespaces
      jsonSchema: InsisPAM
  transformation:
    DefaultTransformationRule:
      additional: insis
      dateFormat: YYYY-MM-DD
      dateTimeFormat: 'YYYY-MM-DDThh:mm:ss'
      extends: risks.life.insis-policy.save
      in: {}
      out:
        - mappings:
            - param: soapAction
              value: modifyApplication
            - param: requestType
              value: ModifyApplRqType
            - param: responseType
              value: ModifyApplRsType
        - mappings:
            - value: null
              payload: InsuranceConditions.PolicyNo
            - value: '-4'
              payload: InsuranceConditions.PolicyState
        - fromIdx:
            array: datamodel.policy.insured.person-objects
          toIdx:
            useSourceIndex: true
          mappings:
            - value: null
              payload: 'Insureds.Insured[n].InsuredObjectID'
            - value: '-1'
              payload: 'Insureds.Insured[n].InsuredEntity.ObjectID'
