list:
  items:
    - value: 1000
    - value: 2000
    - value: 5000
    - value: 10000
    - value: 20000
    - value: 50000
    - value: 100000
    - value: 200000
    - value: 500000
    - value: 1000000
  type: integer
  additionals: {}
