element:
  type: action
  component:
    StaticComponentRule:
      component:
        IceButton:
          themeColor: primary
          variant: flat
  #defaultValue: application.register
  mirror:
    DtMirrorRule:
      dt: go-to-next-page-covers.mirror
