page:
  component: TwoLevelStepperNavigationPage
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.vehicle-details.title
      pageTitleKey: pages.2.application.vehicle-details.title
      shortTitleKey: pages.2.application.vehicle-details.title
  sections:
    - css: small-title
      label:
        ResourceSectionLabelRule:
          labelKey: pages.2.application.vehicle-details.section-title
      component:
        IceArrayFlexSection:
          css: main-side
          arrayElement: policy.insured.vehicle-objects
          behaviourForEmptyRows: hidden
          grid:
            rows:
              - gap: 30px
                gap.xs: 0px
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4 section-subgroup
                    elements:
                      - name: policy.insured.vehicle-objects~owner.options.title
              - gap: 30px
                gap.xs: 0px
                cols:
                  - size: 100%
                    size.xs: 100%
                    css: u-mb-4 section-subgroup
                    elements:
                      - name: policy.insured.vehicle-objects~owner.options
              - gap: 30px
                gap.xs: 0px
                align: start
                css: u-mt-4
                cols:
                  - size: 410px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.lessor-name
              - gap: 30px
                gap.xs: 0px
                align: start
                css: u-mt-4
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.first-name
                  - size: 190px
                    size.xs: 100%
                    elements:
                      - name: policy.insured.vehicle-objects~owner.last-name
              - gap: 30px
                gap.xs: 0px
                align: start
                css: u-mt-4
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.address.city
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.address.zip
              - gap: 30px
                gap.xs: 0px
                align: start
                css: u-mt-4
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.birthdate
              - cols:
                  - size: auto
                    size.xs: 100%
                    css: section-title
                    elements:
                      - name: policy.participants.beneficiaries~title
              - gap: 30px
                gap.xs: 0px
                align: start
                css: u-mt-4
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.participants.beneficiaries~person.first-name
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.participants.beneficiaries~person.last-name
              - gap: 30px
                gap.xs: 0px
                cols:
                  - size: 100%
                    size.xs: 100%
                    sections:
                      - name: drivers
    - component:
        IceFlexSection:
          tags:
            - pull-right
          grid:
            rows:
              - cols:
                  - size: 100%
                    size.xs: 100%
                    elements:
                      - name: continue
                align: space-between
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: button-width-100
    - component:
        IceFlexSection:
          tags:
            - pull-right
          grid:
            rows:
              - cols:
                  - size: 100%
                    size.xs: 100%
                    elements:
                      - name: more-information-needed
                align: space-between
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: main-side text-align-center
    - component:
        IceFlexSection:
          tags:
            - pull-right
          grid:
            rows:
              - cols:
                  - size: none
                    size.xs: 100%
                    css: text-align-right
                    elements:
                      - name: policy.insured.total-premium.amount
                  - size: none
                    size.xs: 100%
                    elements:
                      - name: policy.insured.premium.title
                css: mat-headline u-m-0
                align: center
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: card main-side
