page:
  component: TwoLevelStepperNavigationPage
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.vehicle-details.title
      pageTitleKey: pages.2.application.vehicle-details.title
      shortTitleKey: pages.2.application.vehicle-details.title
  sections:
    - css: small-title
      label:
        ResourceSectionLabelRule:
          labelKey: pages.2.application.vehicle-details.section-title
      component:
        IceArrayFlexSection:
          css: main-side
          arrayElement: policy.insured.vehicle-objects
          behaviourForEmptyRows: hidden
          grid:
            rows:
              - gap: 24px
                gap.xs: 0px
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-3 mat-h3 u-text-medium
                    elements:
                      - name: policy.insured.vehicle-objects~owner.options-title
              - gap: 24px
                gap.xs: 0px
                cols:
                  - size: 100%
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.options
              - gap: 24px
                gap.xs: 0px
                align: start
                cols:
                  - size: 404px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.lessor.name
              - gap: 24px
                gap.xs: 0px
                align: start
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.person.first-name
                  - size: 190px
                    size.xs: 100%
                    elements:
                      - name: policy.insured.vehicle-objects~owner.person.last-name
              - gap: 24px
                gap.xs: 0px
                align: start
                cols:
                  - size: 280px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.address.city
                  - size: 100px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.address.zip
              - gap: 24px
                gap.xs: 0px
                align: start
                cols:
                  - size: 190px
                    size.xs: 100%
                    css: u-mb-4
                    elements:
                      - name: policy.insured.vehicle-objects~owner.person.birthdate
              - cols:
                  - size: 100%
                    css: mat-h3 u-mb-3 u-text-medium
                    elements:
                      - name: additional-audio-video-equipment.title
              - gap: 24px
                gap.xs: 0px
                cols:
                  - size: 100%
                    sections:
                      - name: additional-audio-video-equipment

              - gap: 24px
                gap.xs: 0px
                cols:
                  - size: 100%
                    size.xs: 100%
                    sections:
                      - name: drivers
    - component:
        IceFlexSection:
          tags:
            - pull-right
          grid:
            rows:
              - cols:
                  - size: 100%
                    elements:
                      - name: continue
      css: button-width-100 u-mb-3
    - component:
        IceFlexSection:
          tags:
            - 'pull-right'
          grid:
            rows:
              - cols:
                  - size: 100%
                    css: mat-small
                    elements:
                      - name: more-information-needed
      css: text-align-center hide-on-mobile u-mb-4
    - component:
        InsisMotorPremiumSummarySection:
          tags:
            - pull-right
    - component:
        InsisMotorPolicySummarySection:
          tags:
            - pull-right
