page:
  component: TwoLevelStepperNavigationPage
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.participants.title
      pageTitleKey: pages.2.application.participants.title
      shortTitleKey: pages.2.application.participants.title
  sections:
    - component:
        IceFlexSection:
          tags:
            - 'pull-right'
          grid:
            rows:
              - cols:
                  - size: 100%
                    size.xs: 100%
                    elements:
                      - name: continue
                css: mat-flat-button mat-primary button-white
                align: space-between
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: main-side button-width-100
    - component:
        IceFlexSection:
          tags:
            - 'pull-right'
          grid:
            rows:
              - cols:
                  - size: 100%
                    size.xs: 100%
                    elements:
                      - name: more-information-needed
                align: space-between
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: main-side text-align-center
    - component:
        IceFlexSection:
          tags:
            - 'pull-right'
          grid:
            rows:
              - cols:
                  - size: none
                    size.xs: 100%
                    css: text-align-right
                    elements:
                      - name: policy.insured.total-premium.amount
                  - size: none
                    size.xs: 100%
                    elements:
                      - name: policy.insured.premium.title
                css: mat-headline margin-0
                align: center
                layout.xs: column
                gap: 10px
                gap.xs: 16px
      css: card main-side
