page:
  component: TwoLevelStepperNavigationPage
  validation:
    onElementComponentChange: true
    behaviour: forward
    showMessages: none
    showGrowl: false
    showElementValidation: true
  label:
    ResourcePageLabelRule:
      navigationTitleKey: pages.2.application.drivers.title
      pageTitleKey: pages.2.application.drivers.title
      shortTitleKey: pages.2.application.drivers.title
